### ISSUE TITLE
3-0-stable NotImplementedError (You must implement cancel method for this payment method.)

### ISSUE THREAD

**Issue by simontseng** [spree-contrib/better_spree_paypal_express#171]
looks like spree is required some thing to be implemented now

```
NotImplementedError (You must implement cancel method for this payment method.):
vendor/bundle/ruby/2.2.0/gems/spree_core-3.0.1/app/models/spree/payment_method.rb:69:in `cancel'
vendor/bundle/ruby/2.2.0/gems/spree_core-3.0.1/app/models/spree/payment/processing.rb:72:in `cancel!'
vendor/bundle/ruby/2.2.0/gems/spree_core-3.0.1/app/models/spree/order.rb:631:in `block in after_cancel'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:46:in `each'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:46:in `each'
...
```

any suggestion about this

**Comment by simontseng** [comment]
Does anyone here have the same issues?  I would expect this affects everybody.  Would love to see some discussion here and I don't mind to put in a PR just need someone point me in the right direction.

anybody?

**Comment by leokra** [comment]
I get the same exception when trying to "Cancel" an already paid order in the backend (spree-2-4). And in "app/models/spree/gateway/pay_pal_express.rb" is no cancel-method implemented. 

I'm not sure why not. Wouldn't it make sense to call the already existing refund-method, if the payment is successfully executed and an order cancelled?

**Comment by simontseng** [comment]
+1 for fix

**Comment by sudeepsidhu** [comment]
https://github.com/spree-contrib/better_spree_paypal_express/pull/180 created for this

**Comment by rogosher** [comment]
It does effect everyone : ) Any progress here?
