### ISSUE TITLE
Error due to app/assets/stylesheets/application.css not existing on installation

### ISSUE THREAD

**Issue by joshuapaling** [spree-contrib/better_spree_paypal_express#38]
Version 2.1

When installing with `bundle exec rails g spree_paypal_express:install` I get the following error:

```
      append  app/assets/javascripts/store/all.js
      append  app/assets/javascripts/admin/all.js
      insert  app/assets/stylesheets/application.css
/Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/actions/inject_into_file.rb:99:in `binread': No such file or directory - /Users/joshuapaling/dev/Espionage/Sneakerology_Website_2013/www/app/assets/stylesheets/application.css (Errno::ENOENT)
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/actions/inject_into_file.rb:99:in `replace!'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/actions/inject_into_file.rb:60:in `invoke!'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/actions.rb:95:in `action'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/actions/inject_into_file.rb:31:in `insert_into_file'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/bundler/gems/better_spree_paypal_express-f1a062d84237/lib/generators/spree_paypal_express/install/install_generator.rb:21:in `add_stylesheets'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `block in invoke_all'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `each'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `map'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `invoke_all'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/group.rb:233:in `dispatch'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/railties-4.0.0/lib/rails/generators.rb:156:in `invoke'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/railties-4.0.0/lib/rails/commands/generate.rb:11:in `<top (required)>'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
	from /Users/joshuapaling/.rvm/gems/ruby-1.9.3-p429/gems/railties-4.0.0/lib/rails/commands.rb:49:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

If I add app/assets/stylesheets/application.css and re-run the install, it works fine, and doesn't appear to change application.css in any way.

![screen shot 2013-10-25 at 1 49 59 pm](https://f.cloud.github.com/assets/145042/1405238/b0901cba-3d20-11e3-9731-47e9015c0beb.png)

**Comment by alepore** [comment]
closing super old issues
